# https://circleci.com/docs/2.0/language-javascript/
version: 2
jobs:
  'node-10':
    docker:
      - image: circleci/node:10
    working_directory: ~/geschichte
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test
      - run: yarn run cov:send
  'node-latest':
    docker:
      - image: circleci/node:latest
    working_directory: ~/geschichte
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test
      - run: yarn run cov:send
  publish:
    docker:
      - image: circleci/node:10
    working_directory: ~/geschichte
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn semantic-release
      - run: yarn build-storybook && yarn doc:html && yarn doc:json
      - run: git config user.email "david@vexquisit.com"
      - run: git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - "db:9f:c4:a2:f1:5f:4c:11:fe:dc:63:b8:f2:f2:3f:d6"
      - run: yarn doc:publish

workflows:
  version: 2
  build:
    jobs:
      - 'node-10'
      - 'node-latest'
      - publish:
          filters:
            branches:
              only:
                - master
          requires:
            - 'node-10'
            - 'node-latest'
